apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ruby-runner-deployment
spec:
  template:
    spec:
      imagePullPolicy: IfNotPresent
      repository: ashaninBenjamin/githab-action-example
      ephemeral: true
      volumes:
        - name: bundle
          hostPath:
            path: /mnt/bundle
            type: DirectoryOrCreate
      dockerVolumeMounts:
        - mountPath: /usr/local/bundle
          name: bundle
      # volumeMounts:
      #   - mountPath: /usr/local/bundle
      #     name: bundle
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ruby-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: ruby-runner-deployment
  minReplicas: 1
  maxReplicas: 5
  # Your chosen scaling metrics here
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - ashaninBenjamin/githab-action-example
