version: '3'

volumes:
  bundle:

services:
  rb:
    image: jiffy/app
    build: .
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
