# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: docker/build-push-action@v2
        with:
          tags: ruby-image:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: ruby-image:latest
          run: rspec

  test-on-container:
    runs-on: self-hosted
    container:
      image: ruby:2.6.5-slim-buster
      volumes:
        - bundle:/usr/local/bundle
    steps:
      - name: install gems
        run: bundle install
      - name: run tests
        run: rspec
